PATH_DB="./data/dbpedia_2015_undirected_light.pickle"
PATH_DATA="./data/factkg_"
EVALUATION_FILE_PATH="claim_only/prompting/prompting_claim_only_v0.csv"
SUBGRAPH_FOLDER="subgraph/"
TRAIN_SPLITS=10
VAL_SPLITS=2
TEST_SPLITS=2
account_id = "dfb49774af2be89e53db8eea92e18c83"
cloudfare_api = "Bearer V8u1C20cFoAULg3rwPSWv3oLQDXktZd4lcxxT9YN"
API_BASE_URL = f"https://api.cloudflare.com/client/v4/accounts/{account_id}/ai/run/"
headers = {"Authorization": cloudfare_api}
SAVED_MODEL_FOLDER = "models/"
RESULTS_FOLDER = "results/"
EMBEDDINGS_FILENAME = "embeddings"
DATA_PATH = "data/"
BERT_LAST_LAYER_DIM=[768]
EMBEDDINGS_FILENAME = "embeddings"
DATA_PATH = "data/"